field: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41 # ContentBlocks
fieldLayouts:
  48fac4d8-f125-4fba-a9ef-29a072d8f257:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e75f8e08-e499-444e-b646-97309e1abb2b # Books
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f77be0a-8ee9-4eb6-a99e-a3fa6cf9e6d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b49d5b9-d21a-4e64-b799-37fe5db4ada8 # Three newest?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e2b8f59-c652-435e-b407-421aea35a5f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: af5a6f2d-4fdf-4cfe-b5e8-900a1ae088c5 # Link to all courses?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09bb20a6-940a-4343-b43a-4c4f2e85a298
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 86ab666a-b032-4e32-8f8a-8fa8c46064c5
        userCondition: null
fields:
  9b49d5b9-d21a-4e64-b799-37fe5db4ada8: # Three newest?
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: threeNewest
    instructions: null
    name: 'Three newest?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  af5a6f2d-4fdf-4cfe-b5e8-900a1ae088c5: # Link to all courses?
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: linkToAllCourses
    instructions: null
    name: 'Link to all courses?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  e75f8e08-e499-444e-b646-97309e1abb2b: # Books
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: books
    instructions: null
    name: Books
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: false
      sources:
        - 'section:c4023ed4-c787-4f58-bb1f-1d51b48518c2' # Books
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: books
name: Books
sortOrder: 10
