field: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41 # ContentBlocks
fieldLayouts:
  89894aaf-856c-44f5-bbec-28684d44d4c5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b47d1535-bf95-4240-8817-43e15b459bc1 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0949a24b-8e67-4465-80b0-377a9031c040
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f490c527-58d9-4ac9-bbba-4b4b537e6e0b # description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aaaba8a-cd10-4acb-a8b0-e022f4eab6a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9dfaa653-4e36-4b09-a7a7-e25e81bafdf7 # Certificates
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54be8447-e9ef-4555-89e1-348e3aef1dc3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4888bdf9-ef46-492d-9249-e4582a32611a
        userCondition: null
fields:
  9dfaa653-4e36-4b09-a7a7-e25e81bafdf7: # Certificates
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: certificates
    instructions: null
    name: Certificates
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: false
      sources:
        - 'section:1e364dce-0242-4cfe-8565-03b39ef5bea6' # Certificates
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  b47d1535-bf95-4240-8817-43e15b459bc1: # Headline
    columnSuffix: zpaqikkm
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f490c527-58d9-4ac9-bbba-4b4b537e6e0b: # description
    columnSuffix: wcjavcbt
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: description
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: certificate
name: Certificate
sortOrder: 11
