field: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41 # ContentBlocks
fieldLayouts:
  4d87809c-8769-4d0c-b64a-97cc4ba5b7e8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6a70457e-a328-490d-8e43-da01bd0fb461 # Chapter Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3b90766-9ac9-4e27-9d89-c3154cad5616
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62b88f4a-25d3-4a89-831f-24f78c24f85b # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5adb01f7-8ca2-4746-af4b-308073f51ac7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eaae67db-1946-4fea-92a2-5d8bd0b23f33
        userCondition: null
fields:
  6a70457e-a328-490d-8e43-da01bd0fb461: # Chapter Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: chapterHeadline
    instructions: null
    name: 'Chapter Headline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  62b88f4a-25d3-4a89-831f-24f78c24f85b: # Subtitle
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: subtitle
    instructions: null
    name: Subtitle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: chapter
name: Chapter
sortOrder: 1
