field: ec9f430a-d961-4e4c-ab37-d8de33b78cbe # Lesson Blocks
fieldLayouts:
  9fae110d-aea1-409a-a7a0-13c7c416f722:
    tabs:
      -
        elements:
          -
            fieldUid: b5a5e8a4-7781-466d-b7c8-b084e1de354e # Chapter Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0d67b800-888b-4a29-9351-b7da5f3b7cdb # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0d67b800-888b-4a29-9351-b7da5f3b7cdb: # Subtitle
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: subtitle
    instructions: ''
    name: Subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b5a5e8a4-7781-466d-b7c8-b084e1de354e: # Chapter Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: chapterHeadline
    instructions: ''
    name: 'Chapter Headline'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: chapter
name: Chapter
sortOrder: 1
