field: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41 # ContentBlocks
fieldLayouts:
  2a00fe97-518d-4d8e-b26d-bb1eb355016b:
    tabs:
      -
        elements:
          -
            fieldUid: c28731d1-d362-458e-8210-a901f3f0e4ab # Chart Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  c28731d1-d362-458e-8210-a901f3f0e4ab: # Chart Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: chartHeadline
    instructions: ''
    name: 'Chart Headline'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: chartLine
name: 'Chart - Line'
sortOrder: 12
