field: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41 # ContentBlocks
fieldLayouts:
  2a00fe97-518d-4d8e-b26d-bb1eb355016b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c28731d1-d362-458e-8210-a901f3f0e4ab # Chart Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21455159-e771-4a90-9d96-3dcf08609e1b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bfb3391f-b29e-440e-9e56-9d3439708702
        userCondition: null
fields:
  c28731d1-d362-458e-8210-a901f3f0e4ab: # Chart Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: chartHeadline
    instructions: null
    name: 'Chart Headline'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: chartLine
name: 'Chart - Line'
sortOrder: 12
