field: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41 # ContentBlocks
fieldLayouts:
  f9c6559e-bd2e-4d47-ab1a-6315e2a6d1ef:
    tabs:
      -
        elements:
          -
            fieldUid: 71ac9a76-cabc-44c7-8470-bae1c0d43ed0 # Entry
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d47dbda4-bf10-41c3-b21c-76becadcfa97 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a52f4dfc-42fb-4bda-a12e-0595eab603d7 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  71ac9a76-cabc-44c7-8470-bae1c0d43ed0: # Entry
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: selectedEntry
    instructions: ''
    name: Entry
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources:
        - 'section:2ec41ca2-210b-47c8-97d3-306955a39abb' # Articles
        - 'section:12f99a24-9d48-4fdd-8f1e-fec6cabf9cca' # Lessons
        - 'section:433733b6-53ef-4e88-b871-7518468484e7' # Portfolio
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  a52f4dfc-42fb-4bda-a12e-0595eab603d7: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  d47dbda4-bf10-41c3-b21c-76becadcfa97: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: entryLink
name: Entry
sortOrder: 13
