field: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41 # ContentBlocks
fieldLayouts:
  3d2cd129-2a56-4ac2-9542-8cfc3a2067e4:
    tabs:
      -
        elementCondition: null
        name: Content
        uid: b6f090b5-cc79-491c-83d9-8c16475598b9
        userCondition: null
handle: hackerrank
name: HackerRank
sortOrder: 15
