field: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41
fieldLayouts:
  237bf740-80eb-4f66-b362-4f05ec0604b6:
    tabs:
      -
        fields:
          5c01d860-2ec5-4205-936e-583524bb8264:
            required: true
            sortOrder: 2
          6a498afe-8881-4b4d-bd9e-f128e6d2ac6e:
            required: true
            sortOrder: 3
          b05c4334-9b2d-4f18-8916-c65a9c521861:
            required: true
            sortOrder: 1
          d6f9cc1f-1608-4ae7-a083-d0924ba71f47:
            required: false
            sortOrder: 4
        name: Content
        sortOrder: 1
fields:
  5c01d860-2ec5-4205-936e-583524bb8264:
    contentColumnType: text
    fieldGroup: null
    handle: imageAlt
    instructions: ''
    name: 'Image AltText'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
  6a498afe-8881-4b4d-bd9e-f128e6d2ac6e:
    contentColumnType: text
    fieldGroup: null
    handle: imageCapt
    instructions: ''
    name: 'Image Caption'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: language
    type: craft\redactor\Field
  b05c4334-9b2d-4f18-8916-c65a9c521861:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowedKinds: null
      defaultUploadLocationSource: 'volume:3b363f5e-4ee5-4536-b78c-b514bf1a0c7a'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: ''
      restrictFiles: ''
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:3b363f5e-4ee5-4536-b78c-b514bf1a0c7a'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d6f9cc1f-1608-4ae7-a083-d0924ba71f47:
    contentColumnType: boolean
    fieldGroup: null
    handle: imageIsFigure
    instructions: ''
    name: 'Image Is Figure'
    searchable: true
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: image
name: Image
sortOrder: 5
