field: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41 # ContentBlocks
fieldLayouts:
  e805ccd1-3547-4bf0-8b3d-565578a887d1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 471da32a-34da-4c05-b7c6-e4bc67adca25 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab9356f8-77ad-4efd-926c-810c0043b6d2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 925f30f1-9ac9-4d22-b2af-07e8f469336c
        userCondition: null
fields:
  471da32a-34da-4c05-b7c6-e4bc67adca25: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: infoBox
name: 'Info Box'
sortOrder: 4
