field: ec9f430a-d961-4e4c-ab37-d8de33b78cbe # Lesson Blocks
fieldLayouts:
  744c3232-cab0-4672-889e-25efe2cb6cc8:
    tabs:
      -
        elements:
          -
            fieldUid: 023232ef-4d79-4571-896b-9146438b66bb # Task text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  023232ef-4d79-4571-896b-9146438b66bb: # Task text
    columnSuffix: fgmzmcco
    contentColumnType: text
    fieldGroup: null
    handle: taskText
    instructions: ''
    name: 'Task text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: taskDone
name: 'Task Done'
sortOrder: 5
