field: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41 # ContentBlocks
fieldLayouts:
  639bbea6-94c0-45a9-be44-ffc374bd8307:
    tabs:
      -
        elements:
          -
            fieldUid: f73c4dce-8cb4-431f-adb5-a9be1f4059cb # Language
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3ebdee02-2eb1-48f4-8b4b-4f45f3bfbae9 # Username
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 19285c32-e1f8-42c0-97ff-59f16dbb52af # Hostname
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 925133d6-79dc-4f13-9cbc-3752c2eff691 # Terminal Dump
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cabe8fa0-a9ef-4a18-ab9d-4b3b69cd2f3a # Terminal Input Only
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3ebdee02-2eb1-48f4-8b4b-4f45f3bfbae9: # Username
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: terminalUserName
    instructions: ''
    name: Username
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  19285c32-e1f8-42c0-97ff-59f16dbb52af: # Hostname
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: terminalHostName
    instructions: ''
    name: Hostname
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  925133d6-79dc-4f13-9cbc-3752c2eff691: # Terminal Dump
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: terminalDump
    instructions: ''
    name: 'Terminal Dump'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cabe8fa0-a9ef-4a18-ab9d-4b3b69cd2f3a: # Terminal Input Only
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: terminalInputOnly
    instructions: ''
    name: 'Terminal Input Only'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  f73c4dce-8cb4-431f-adb5-a9be1f4059cb: # Language
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: terminalLanguage
    instructions: ''
    name: Language
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - BASH
            -
              - value
              - bash
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - PowerShell
            -
              - value
              - powershell
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: terminalDump
name: 'Terminal Dump'
sortOrder: 7
