field: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41 # ContentBlocks
fieldLayouts:
  639bbea6-94c0-45a9-be44-ffc374bd8307:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f73c4dce-8cb4-431f-adb5-a9be1f4059cb # Language
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02e843aa-eeee-4f0a-927c-c4cf6071e534
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7ed843f8-2709-4ad0-b32d-e234ed22f289 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60c93968-58dc-4e03-bc5a-bb9a31d7c566
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: cabe8fa0-a9ef-4a18-ab9d-4b3b69cd2f3a # Terminal Input Only
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 630a090a-6aee-4a77-b016-02889b9dcbdb
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 3ebdee02-2eb1-48f4-8b4b-4f45f3bfbae9 # Username
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 734411f8-32c1-4434-9630-470e18013998
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 19285c32-e1f8-42c0-97ff-59f16dbb52af # Hostname
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc0d57db-0316-4ea6-a954-e60e12ce12c7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 925133d6-79dc-4f13-9cbc-3752c2eff691 # Terminal Dump
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f4ff289-738a-486b-a4bd-dcc8522b467f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 517002ca-d9e1-42d7-867b-e3d7ce622d45
        userCondition: null
fields:
  3ebdee02-2eb1-48f4-8b4b-4f45f3bfbae9: # Username
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: terminalUserName
    instructions: null
    name: Username
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7ed843f8-2709-4ad0-b32d-e234ed22f289: # Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: terminalColor
    instructions: null
    name: Color
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Default (black)'
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Attacker
            -
              - value
              - attacker
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Victim
            -
              - value
              - victim
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Neutral
            -
              - value
              - neutral
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  19285c32-e1f8-42c0-97ff-59f16dbb52af: # Hostname
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: terminalHostName
    instructions: null
    name: Hostname
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  925133d6-79dc-4f13-9cbc-3752c2eff691: # Terminal Dump
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: terminalDump
    instructions: null
    name: 'Terminal Dump'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cabe8fa0-a9ef-4a18-ab9d-4b3b69cd2f3a: # Terminal Input Only
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: terminalInputOnly
    instructions: null
    name: 'Terminal Input Only'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  f73c4dce-8cb4-431f-adb5-a9be1f4059cb: # Language
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: terminalLanguage
    instructions: null
    name: Language
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - BASH
            -
              - value
              - BASH
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - PowerShell
            -
              - value
              - PowerShell
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: terminalDump
name: 'Terminal Dump'
sortOrder: 7
