field: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41
fieldLayouts:
  483d2033-0c96-427e-a49a-51c130ab618c:
    tabs:
      -
        fields:
          57a8d48f-2781-4975-b7ff-b3b5efd7c470:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  57a8d48f-2781-4975-b7ff-b3b5efd7c470:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 2
