color: null
fieldLayouts:
  c3594ae3-1be5-47ff-8355-d3504b300d1b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 09509171-51ce-4f5e-807b-6f6840a0f23a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 72a349c8-b7c8-4301-81a5-7301f5cc1058 # Article Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8ef007a-f2e3-4cae-8085-be149ad0540e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f9145c5e-c78a-4a33-950f-a91359723426 # Selfcontained
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d89f0b2-cc68-4895-9ed7-31f1752b0607
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 3d5543fa-7b96-4f00-baff-e330b237625b # Not mobile friendly
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a3b2c36-eb12-4a75-b651-0e920c8a7df4
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f147e4fb-5b9b-40b9-9b58-51fa33d89e32 # Article Teaser
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 984241c1-37dd-4082-9c78-ee862fe8c3fc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41 # ContentBlocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a759399b-76b4-4916-b5e0-d73eb9a75d8e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e50147d2-5548-4c85-b0aa-143c97afcf80
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3e4dc06a-6af1-479b-a120-662a4500d935 # Artikkel tema
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 394bd929-0df4-4786-9b0a-4bd5b62434af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6bcc3fb3-fa1a-42c3-b33b-5f61432e08ca # Artikkel type
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74d064c6-4329-4a96-b13f-d0683fd89c0b
            userCondition: null
            warning: null
            width: 100
        name: Metadata
        uid: 23be7a8b-5168-4b1a-a7b4-670082fa4917
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7701d10a-74fb-40fb-a7aa-7e184bb97f05 # SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcd13e42-5f31-4cd9-bcc5-ad98e4a811b5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c1769912-6758-4fbd-9f12-d37a9fa32253 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50b8ee05-f5ed-4551-9220-42cc1951d515
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: e2ec5244-c4a2-4cdd-8dc0-a14f7c247c19
        userCondition: null
handle: aboveContent
hasTitleField: true
icon: null
name: 'Above Content'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
