color: null
fieldLayouts:
  89894aaf-856c-44f5-bbec-28684d44d4c5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b47d1535-bf95-4240-8817-43e15b459bc1
            handle: null
            includeInCards: true
            instructions: null
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0949a24b-8e67-4465-80b0-377a9031c040
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f490c527-58d9-4ac9-bbba-4b4b537e6e0b
            handle: null
            includeInCards: false
            instructions: null
            label: description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aaaba8a-cd10-4acb-a8b0-e022f4eab6a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9dfaa653-4e36-4b09-a7a7-e25e81bafdf7
            handle: null
            includeInCards: false
            instructions: null
            label: Certificates
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54be8447-e9ef-4555-89e1-348e3aef1dc3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4888bdf9-ef46-492d-9249-e4582a32611a
        userCondition: null
handle: certificate
hasTitleField: false
icon: null
name: Certificate
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
