color: null
fieldLayouts:
  2a00fe97-518d-4d8e-b26d-bb1eb355016b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c28731d1-d362-458e-8210-a901f3f0e4ab
            handle: null
            includeInCards: true
            instructions: null
            label: 'Chart Headline'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21455159-e771-4a90-9d96-3dcf08609e1b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bfb3391f-b29e-440e-9e56-9d3439708702
        userCondition: null
handle: chartLine
hasTitleField: false
icon: null
name: 'Chart - Line'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
