fieldLayouts:
  0e30a4bc-8661-41f6-b10a-467d7d27b98e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 93d39a6a-48eb-4f78-afb1-8fd74053ce15 # Kurs bilde
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c418c358-5082-4c2e-bc17-cb8c9175b592 # Instruktør
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 12c8b9da-5b5a-4bd7-a51e-4116181081ad # Kurs beskrivelse
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6f5f5cbf-7ead-4f94-9ed2-42c81ae3a3d3 # Kurs anmeldelse score
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f733eaac-e1d6-428e-a5e6-5e9c1b8450df # Kurs anmeldelse sitat
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6ed30be3-319a-4469-a458-a70309e3e179 # Kurs anmeldelse
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4a837336-d09a-492d-aa97-3c29b176ecc7 # Kurs platform
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0e2235ec-098b-4add-9c16-2a51cb50b5e3 # Kurs karakter
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c2cadeae-b406-4376-a7bb-822c8d077ca2 # Kurs tema
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 44f8fa56-23f3-4d1e-8231-4e7f46c9af46 # Fullført dato
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9096bb19-2f4d-4b40-91f7-7f0d84ee7b01 # Varighet
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d9a0abe6-89dd-4688-a0ac-6d584524c3c2 # Kursbevis
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Metadata
        sortOrder: 2
handle: courses
hasTitleField: true
name: Kurs
section: b3979b7e-2d54-4b6f-89ec-5ef480431d82 # Kurs
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
