color: null
fieldLayouts:
  51f04f76-d8a6-4257-8038-4edc281a3a5d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0e94656b-cd99-469f-af11-2e559215536b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41 # ContentBlocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 574b6d03-78df-48f1-80c3-5e4cfba2c660
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c1afd018-8227-4306-b1be-4b923df06ec1
        userCondition: null
handle: course
hasTitleField: true
icon: null
name: 'My courses'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: language
