color: orange
fieldLayouts:
  7e83945a-84c7-442f-a4f6-a62dac941a55:
    cardView:
      - 'layoutElement:f0b42089-2efe-4452-bd12-42c6464c5fe9'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-10T11:25:48+00:00'
            elementCondition: null
            fieldUid: a2c9fa7f-4706-4b49-ad49-f09d9a9ebc10 # ContentBlocks - Courses - Courses
            handle: null
            includeInCards: true
            instructions: null
            label: Courses
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0b42089-2efe-4452-bd12-42c6464c5fe9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T11:25:48+00:00'
            elementCondition: null
            fieldUid: 9b49d5b9-d21a-4e64-b799-37fe5db4ada8 # ContentBlocks - Books - Three newest?
            handle: null
            includeInCards: false
            instructions: null
            label: 'Three newest?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2695da21-0f20-4b7a-8ae5-5d36b8dc8c5d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-12-10T11:25:48+00:00'
            elementCondition: null
            fieldUid: af5a6f2d-4fdf-4cfe-b5e8-900a1ae088c5 # ContentBlocks - Link to all?
            handle: null
            includeInCards: false
            instructions: null
            label: 'Include link to overview?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa2bcc71-6a3c-4d01-a23a-642559f7ac80
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 35392619-a098-42d0-bd46-7505311f4efb
        userCondition: null
handle: coursesField
hasTitleField: false
icon: graduation-cap
name: Courses
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
