color: null
fieldLayouts:
  9f57dd9b-dc65-49af-81d2-e0534dcbc236:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-14T11:53:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8256463f-2f2f-4e1a-86af-bfd9714f8f9a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-14T11:53:52+00:00'
            elementCondition: null
            fieldUid: f147e4fb-5b9b-40b9-9b58-51fa33d89e32 # Teaser
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aaf83856-73aa-4e46-a8de-528d3361afd0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-14T11:53:52+00:00'
            elementCondition: null
            fieldUid: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41 # ContentBlocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82607b08-db07-4d8b-a313-f1fb28dd8665
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d49bf85a-9314-4944-a034-f3f8d5d0d34c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-14T11:53:52+00:00'
            elementCondition: null
            fieldUid: 3e4dc06a-6af1-479b-a120-662a4500d935 # Artikkel tema
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: beae494b-dd71-47cf-ba74-bfced74c0acc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-14T11:53:52+00:00'
            elementCondition: null
            fieldUid: c6f23113-dc98-46d8-8a58-8837396917aa # CTF Platfom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78e927cc-0394-41df-825d-a8a1f162c2c9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-14T11:53:52+00:00'
            elementCondition: null
            fieldUid: 82658716-4746-4ec3-9c32-b565286277bc # CTF Difficulty
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5e21700-5a90-4c2c-b923-441b1b5304ba
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-14T11:53:52+00:00'
            elementCondition: null
            fieldUid: 8c4f446d-dc3c-443f-b043-fb2a3c5e2aff # CTF Points
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 419a3746-cf22-4e39-bf21-7a67217cdf8d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-14T11:53:52+00:00'
            elementCondition: null
            fieldUid: aad6c628-7e5f-4c95-9383-e39426be72f7 # CTF Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e61f8ee-9f00-40c7-aca0-9942c1139f97
            userCondition: null
            warning: null
            width: 100
        name: Metadata
        uid: 45a36026-89ca-43cd-b3ac-ddfea6a56a4e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-14T11:53:52+00:00'
            elementCondition: null
            fieldUid: 7701d10a-74fb-40fb-a7aa-7e184bb97f05 # SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7d73db4-419b-49fa-863f-203f0ef38743
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-14T11:53:52+00:00'
            elementCondition: null
            fieldUid: c1769912-6758-4fbd-9f12-d37a9fa32253 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f4fc790-8ec7-4160-bbeb-5cb3643a351d
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: e79d137b-6fc3-46c1-9946-9d1cdb68f93b
        userCondition: null
handle: ctfWriteup_default
hasTitleField: true
icon: null
name: 'CTF Writeup - Default'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
