color: orange
fieldLayouts:
  f9c6559e-bd2e-4d47-ab1a-6315e2a6d1ef:
    cardView:
      - 'layoutElement:bb2b0179-3ba1-47c4-9c82-a684af3b537e'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-10T15:04:04+00:00'
            elementCondition: null
            fieldUid: 71ac9a76-cabc-44c7-8470-bae1c0d43ed0 # Selected Entry
            handle: null
            includeInCards: true
            instructions: null
            label: Entry
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb2b0179-3ba1-47c4-9c82-a684af3b537e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T15:04:04+00:00'
            elementCondition: null
            fieldUid: b47d1535-bf95-4240-8817-43e15b459bc1 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5ee8413-ec04-4976-892c-76cdfd6967a3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T15:04:04+00:00'
            elementCondition: null
            fieldUid: 57a8d48f-2781-4975-b7ff-b3b5efd7c470 # ContentBlocks - Text
            handle: null
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59b282b6-be5d-43eb-b639-7d3d84c95ef1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ffd22ab2-0340-4dba-a897-c868a1145f98
        userCondition: null
handle: entryLink
hasTitleField: false
icon: newspaper
name: Entry
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
