color: null
fieldLayouts:
  f9c6559e-bd2e-4d47-ab1a-6315e2a6d1ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 71ac9a76-cabc-44c7-8470-bae1c0d43ed0
            handle: null
            includeInCards: true
            instructions: null
            label: Entry
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb2b0179-3ba1-47c4-9c82-a684af3b537e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d47dbda4-bf10-41c3-b21c-76becadcfa97
            handle: headline
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5ee8413-ec04-4976-892c-76cdfd6967a3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a52f4dfc-42fb-4bda-a12e-0595eab603d7
            handle: text
            includeInCards: false
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59b282b6-be5d-43eb-b639-7d3d84c95ef1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ffd22ab2-0340-4dba-a897-c868a1145f98
        userCondition: null
handle: entryLink
hasTitleField: false
icon: null
name: Entry
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
