color: purple
fieldLayouts:
  eb82eaed-4b98-4191-b384-f755ca3fa0a2:
    cardView:
      - 'layoutElement:81fdb2a2-6302-4b7f-966f-a3246fc428cd'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-10T15:40:22+00:00'
            elementCondition: null
            fieldUid: dc63f038-3a87-428d-9230-20a288f905da # ContentBlocks - File Content - File type
            handle: null
            includeInCards: true
            instructions: null
            label: 'File type'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81fdb2a2-6302-4b7f-966f-a3246fc428cd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T15:40:22+00:00'
            elementCondition: null
            fieldUid: 5dd9f4f3-fb1c-4d81-b3fd-2309b56563f0 # ContentBlocks - File Content - Filname
            handle: null
            includeInCards: false
            instructions: null
            label: Filname
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f643cfcc-7a8b-43e3-b6cf-a4caab6e2f1a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T15:40:22+00:00'
            elementCondition: null
            fieldUid: ed101e61-62b0-40c5-a8d4-b5d30624f1d2 # ContentBlocks - File Content - File content
            handle: null
            includeInCards: false
            instructions: null
            label: 'File content'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad5fcaa7-cbfd-47e8-9808-0584a9c20d6f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T15:40:22+00:00'
            elementCondition: null
            fieldUid: f4121429-712b-4587-839a-e0a1db5d946a # ContentBlocks - File Content - Line Numbers
            handle: null
            includeInCards: false
            instructions: null
            label: 'Line Numbers'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac0952e5-12f9-409f-a311-27a3513a864f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e0526371-b5a0-4bb7-b04a-989a396b2bbd
        userCondition: null
handle: fileContent
hasTitleField: false
icon: brackets-curly
name: 'File Content'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
