fieldLayouts:
  7df2136f-9c93-4b38-8d94-0c32ea3e12b5:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 72a349c8-b7c8-4301-81a5-7301f5cc1058
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: baf14ed6-b329-41e7-b9b5-4ff5d8ed2cdf
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f147e4fb-5b9b-40b9-9b58-51fa33d89e32
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 84196158-704f-46cd-9cc5-cfe49666f56e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: c3d8fdbe-5d3a-4a09-a91f-2da6060ece41
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 3e4dc06a-6af1-479b-a120-662a4500d935
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 6bcc3fb3-fa1a-42c3-b33b-5f61432e08ca
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Metadata
        sortOrder: 2
handle: guides
hasTitleField: true
name: Guides
section: 2ec41ca2-210b-47c8-97d3-306955a39abb # Articles
sortOrder: 1
titleFormat: ''
