color: null
fieldLayouts:
  b1d88c81-94f1-4548-802e-eefa5b51957b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ac148d8c-048e-40df-921a-e1f850f675b1
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b770208-2344-4487-b36d-96e449b71067
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b7b92d43-ba38-4a42-8cdb-d7b4989964bc
            handle: imageAlt
            includeInCards: true
            instructions: null
            label: 'Image AltText'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e18528b-f684-4f8d-8e87-27e43ccfaa0a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 922f9488-fac0-4f97-88a1-f12f6b41c77d
            handle: imageCapt
            includeInCards: false
            instructions: null
            label: 'Image Caption'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0356baa5-6868-4bf1-adf7-d4fe9783952a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 952b5bbe-a4d3-4785-9315-9c1a8b0b6dc1
            handle: imageIsFigure
            includeInCards: false
            instructions: null
            label: 'Image Is Figure'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61470c46-6309-40f3-8714-947c23ab957e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4edca621-7cc9-4431-91ec-1b17acba0128
        userCondition: null
handle: image2
hasTitleField: false
icon: null
name: 'Image 2'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
