color: null
fieldLayouts:
  e805ccd1-3547-4bf0-8b3d-565578a887d1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-10T12:33:40+01:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8c7cb1bb-1259-4ab9-867d-cf007b2cd04c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-10T12:33:40+01:00'
            elementCondition: null
            fieldUid: 471da32a-34da-4c05-b7c6-e4bc67adca25 # ContentBlocks - Info Box - Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab9356f8-77ad-4efd-926c-810c0043b6d2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 925f30f1-9ac9-4d22-b2af-07e8f469336c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-10T12:33:40+01:00'
            elementCondition: null
            fieldUid: 9bfb520d-0d98-4906-9d30-74ca1c638982 # Lesson Blocks - Info Box - Text
            handle: text2
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c70feb04-6360-4b37-96f1-dc85fa44e45b
            userCondition: null
            warning: null
            width: 100
        name: 'Merged Fields'
        uid: 64f563e2-a3fd-4175-b629-697a95ca2e11
        userCondition: null
handle: infoBox
hasTitleField: true
icon: null
name: 'Info Box'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
