color: null
fieldLayouts:
  5c45fdfa-cab4-43ab-908b-106c76c81ad8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7f7e310e-719e-47bb-8571-d951a95e655e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9bfb520d-0d98-4906-9d30-74ca1c638982 # Lesson Blocks - Info Box - Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c70feb04-6360-4b37-96f1-dc85fa44e45b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6310f987-fe4b-43bb-85f8-d49f99df1588
        userCondition: null
handle: infoBox2
hasTitleField: false
icon: null
name: 'Info Box 2'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
