color: purple
fieldLayouts:
  9cc96a98-cb72-42f3-943c-697cbeb31c05:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-01T16:13:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bc4e9234-abe3-4de0-a9d8-ab6bc43a4cab # Math Field
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 462e779b-d5ab-4c89-a8e6-5facf175095b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 79962c79-3d6a-4a76-910b-8c7e81d051c6
        userCondition: null
handle: mathFormula
hasTitleField: false
icon: function
name: 'Math Formula'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
