color: null
fieldLayouts:
  cdbb61ca-cfb0-41b0-ae6a-515ad8a5c8ed:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 140547c2-d448-4661-a3b7-4ba7e82104f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f96fb1c8-21d9-45ec-bc75-5792dd3b3c5b # ContentBlocks - Quote - Quote
            handle: null
            includeInCards: true
            instructions: null
            label: Quote
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f30f068-9acc-468e-86d6-75a30bad7f0d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: df878c7b-721d-488d-bdbb-337645b1b30c
        userCondition: null
handle: quote
hasTitleField: false
icon: null
name: Quote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
