color: lime
fieldLayouts:
  cdbb61ca-cfb0-41b0-ae6a-515ad8a5c8ed:
    cardView:
      - 'layoutElement:7f30f068-9acc-468e-86d6-75a30bad7f0d'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-10T15:42:39+00:00'
            elementCondition: null
            fieldUid: f96fb1c8-21d9-45ec-bc75-5792dd3b3c5b # ContentBlocks - Quote - Quote
            handle: null
            includeInCards: true
            instructions: null
            label: Quote
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f30f068-9acc-468e-86d6-75a30bad7f0d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: df878c7b-721d-488d-bdbb-337645b1b30c
        userCondition: null
handle: quote
hasTitleField: false
icon: quotes
name: Quote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
