color: null
fieldLayouts:
  ab8d7126-85b9-4394-8d20-87b0a820e577:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9566cd8c-5d0d-40b0-b7b0-ef1bfdd08e66
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f773f4a-97cc-41d5-9fb6-2016426d4da5 # Lesson Blocks - Text - Text
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58ed0df2-9ad7-46ea-8e70-51c74cf41fb7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4fbaf6ad-66b7-4fc9-9f2c-2c1aa15ceef8
        userCondition: null
handle: text2
hasTitleField: false
icon: null
name: 'Text 2'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
