color: lime
fieldLayouts:
  483d2033-0c96-427e-a49a-51c130ab618c:
    cardView:
      - 'layoutElement:41cc62c2-d561-4a83-8cbc-04218b20d000'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-10T11:17:17+00:00'
            elementCondition: null
            fieldUid: 57a8d48f-2781-4975-b7ff-b3b5efd7c470 # ContentBlocks - Text
            handle: null
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41cc62c2-d561-4a83-8cbc-04218b20d000
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3207cffd-c160-411e-bb3a-134248fb0d19
        userCondition: null
handle: text
hasTitleField: false
icon: text
name: Text
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
