color: green
fieldLayouts:
  193f9791-8fa1-48e5-8767-0dfe987379c0:
    tabs:
      -
        elementCondition: null
        name: Content
        uid: 35d0251b-20a0-4387-96c2-6e7b5fec7c3e
        userCondition: null
handle: tryhackme
hasTitleField: false
icon: bolt
name: TryHackMe
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
