headingLevels: false
name: Simple
options:
  code:
    indentSequence: '  '
toolbar:
  - bold
  - italic
  - underline
  - strikethrough
  - '|'
  - subscript
  - superscript
  - '|'
  - bulletedList
  - numberedList
  - outdent
  - indent
  - '|'
  - link
