handle: articleType
name: Artikkeltype
siteSettings:
  2fc7f7b8-2f9d-43dd-977b-8c7b29763e54: # Skarshaugs.no/en
    hasUrls: true
    template: ''
    uriFormat: 'articletype/{slug}'
  d81b7a18-6d93-471a-ba57-99544b0c585b: # Skarshaugs.no
    hasUrls: true
    template: ''
    uriFormat: 'artikkeltype/{slug}'
structure:
  maxLevels: null
  uid: da3cf781-40c9-4d1b-a2d1-4c8100d51740
