handle: articleType
name: Artikkeltype
siteSettings:
  2fc7f7b8-2f9d-43dd-977b-8c7b29763e54:
    hasUrls: true
    template: ''
    uriFormat: 'articletype/{slug}'
  87380fe3-7806-4c94-93c9-d75509f157cd:
    hasUrls: true
    template: ''
    uriFormat: 'artikkeltype/{slug}'
  d81b7a18-6d93-471a-ba57-99544b0c585b:
    hasUrls: true
    template: ''
    uriFormat: 'artikkeltype/{slug}'
structure:
  maxLevels: null
  uid: da3cf781-40c9-4d1b-a2d1-4c8100d51740
