defaultPlacement: end
fieldLayouts:
  d1f0de43-8c2c-4598-b872-4a4a29919c29:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 2dd9d56f-9728-4f09-a218-535ba1bd41c0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 25775f64-f9d9-4946-8276-c00f0a0430a8
        userCondition: null
handle: coursePlatform
name: Kursplatform
siteSettings:
  2fc7f7b8-2f9d-43dd-977b-8c7b29763e54: # haxor.no/en
    hasUrls: true
    template: null
    uriFormat: 'kursplatform/{slug}'
  d81b7a18-6d93-471a-ba57-99544b0c585b: # haxor.no/no
    hasUrls: true
    template: null
    uriFormat: 'kursplatform/{slug}'
structure:
  maxLevels: 1
  uid: 677b1027-87e7-4644-b7f8-d32f4c8199e1
