defaultPlacement: end
fieldLayouts:
  c776377e-f0a5-441f-a2f7-c6adb8b96f88:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 72a349c8-b7c8-4301-81a5-7301f5cc1058 # Article Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: baf14ed6-b329-41e7-b9b5-4ff5d8ed2cdf # Article Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: ctfPlatform
name: 'CTF Platform'
siteSettings:
  2fc7f7b8-2f9d-43dd-977b-8c7b29763e54: # haxor.no/en
    hasUrls: true
    template: null
    uriFormat: 'ctf-platform/{slug}'
  d81b7a18-6d93-471a-ba57-99544b0c585b: # haxor.no/no
    hasUrls: true
    template: null
    uriFormat: 'ctf-platform/{slug}'
structure:
  maxLevels: 1
  uid: 466eb65a-62e8-4d15-a226-b416573399f6
