handle: theme
name: Tema
siteSettings:
  2fc7f7b8-2f9d-43dd-977b-8c7b29763e54: # haxor.no/en
    hasUrls: true
    template: ''
    uriFormat: 'theme/{slug}'
  d81b7a18-6d93-471a-ba57-99544b0c585b: # haxor.no
    hasUrls: true
    template: ''
    uriFormat: 'tema/{slug}'
structure:
  maxLevels: null
  uid: 648740f0-bafd-4679-8cfc-3e0d367aa2b2
