altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  c0cfb397-da13-4c67-b7cd-8f76b4b1bebd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-10T18:38:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 1876fd70-a8ee-4bb1-b3f7-cb6348090c73
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-12-10T18:39:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 07623741-4096-4856-8254-e8fdadd7bcf8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0d806eae-3ccc-44ef-9c66-1b2f926f6bdd
        userCondition: null
fs: thumbnails
handle: thumbnails
name: Thumbnails
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: none
transformFs: ''
transformSubpath: ''
