columnSuffix: null
contentColumnType: string
fieldGroup: 26a433d6-c7ff-4f42-8acb-7bcc035fc4d2 # Course
handle: achievementBadge
instructions: null
name: 'Achievement Badge'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:4660b070-063e-4eb7-b897-c5273ae300c3' # Icons and Badges
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:4660b070-063e-4eb7-b897-c5273ae300c3' # Icons and Badges
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:4660b070-063e-4eb7-b897-c5273ae300c3' # Icons and Badges
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
