columnSuffix: null
handle: articleTeaser
instructions: null
name: 'Article Teaser'
searchable: true
settings:
  byteLimit: null
  charLimit: 70
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
