columnSuffix: null
handle: articleSubject
instructions: null
name: 'Artikkel tema'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: 0
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  source: 'group:7755a334-0698-4415-ab30-b1fddb17b7a7' # Tema
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
