columnSuffix: null
handle: articleImageCaption
instructions: null
name: 'Article Image Caption'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: fc40ce26-28fb-475a-b6b7-696c795f5f18 # Simple text and link
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: language
type: craft\ckeditor\Field
