contentColumnType: string(280)
handle: articleTeaser
instructions: ''
name: 'Article Teaser'
searchable: true
settings:
  byteLimit: null
  charLimit: 70
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
