columnSuffix: null
contentColumnType: string
handle: courseGrade
instructions: ''
name: 'Course Grade'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Bestått
        -
          - value
          - pass
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - A
        -
          - value
          - a
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - B
        -
          - value
          - b
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - C
        -
          - value
          - c
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - D
        -
          - value
          - d
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - E
        -
          - value
          - e
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - F
        -
          - value
          - f
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
