columnSuffix: null
handle: courseReview
instructions: null
name: 'Course Review'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: bcea5606-ec0b-4bea-b4ab-b4c0eebb7851 # Default
  defaultTransform: ''
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: language
type: craft\ckeditor\Field
