columnSuffix: null
handle: coursePlatform
instructions: null
name: 'Course Platform'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: 1
  localizeRelations: false
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: false
  source: 'group:6f1a1285-4249-4f2a-9773-1b8a2cb33fd9' # Kursplatform
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
