columnSuffix: null
contentColumnType: integer(10)
handle: courseLengthHours
instructions: ''
name: 'Course Length (hours)'
searchable: false
settings:
  decimals: 0
  defaultValue: 0
  max: null
  min: 0
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
