columnSuffix: null
handle: courseLengthMinutes
instructions: null
name: 'Course Length (min)'
searchable: false
settings:
  decimals: 0
  defaultValue: 0
  max: 59
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
