columnSuffix: null
handle: credits
instructions: null
name: Credits
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: fc40ce26-28fb-475a-b6b7-696c795f5f18 # Simple text and link
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
