columnSuffix: vsuljzdb
handle: ctfDifficulty
instructions: null
name: 'CTF Difficulty'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Info
        -
          - value
          - info
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Very Easy'
        -
          - value
          - veryeasy
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Easy
        -
          - value
          - easy
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Medium
        -
          - value
          - medium
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Hard
        -
          - value
          - hard
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Insane
        -
          - value
          - insane
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
