columnSuffix: baxtmxqs
contentColumnType: integer(10)
handle: ctfPoints
instructions: ''
name: 'CTF Points'
searchable: false
settings:
  decimals: 0
  defaultValue: 0
  max: null
  min: 0
  prefix: null
  previewCurrency: ''
  previewFormat: none
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
