columnSuffix: wcjavcbt
handle: description
instructions: null
name: 'ContentBlocks - Certificate - description'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: aebd25a6-0dc4-4348-a7dd-cf11b6168ef5 # Simple 2
  defaultTransform: ''
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
