columnSuffix: wcjavcbt
handle: description
instructions: null
name: 'ContentBlocks - Certificate - description'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 4ff4b6be-5f03-4236-a01d-2b5125c03d66 # Simple
  defaultTransform: ''
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
