columnSuffix: zpaqikkm
handle: headline
instructions: null
name: Headline
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 12e90aa7-cbb6-4d63-b1d5-f35385429f7c # Headline
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
