columnSuffix: zpaqikkm
handle: headline
instructions: null
name: Headline
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  css: null
  cssFile: null
  defaultTransform: null
  fullGraphqlData: false
  headingLevels: false
  js: null
  jsFile: null
  options: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - subscript
    - superscript
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
