columnSuffix: null
handle: ingress
instructions: null
name: Intro
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: ''
  ckeConfig: aebd25a6-0dc4-4348-a7dd-cf11b6168ef5 # Simple 2
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
