columnSuffix: null
handle: ingress
instructions: null
name: Intro
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: ''
  css: null
  cssFile: null
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  fullGraphqlData: false
  headingLevels: false
  js: null
  jsFile: Simple.json
  options: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  toolbar:
    - bold
    - italic
    - underline
    - strikethrough
    - '|'
    - subscript
    - superscript
    - '|'
    - bulletedList
    - numberedList
    - outdent
    - indent
    - '|'
    - link
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
