columnSuffix: null
contentColumnType: string
fieldGroup: acdcb75a-569c-4ec7-b2ab-9de3e91d8604 # Lessons
handle: lessonBlocks
instructions: ''
name: 'Lesson Blocks'
searchable: false
settings:
  contentTable: '{{%matrixcontent_lessonblocks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
