columnSuffix: null
handle: lessonBlocks
instructions: null
name: 'Lesson Blocks'
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 13e06e3a-25c9-4b11-aa21-6b5b768d5fea # Send in answer
    - 14fc49ec-a2e2-4953-a06d-e4c93142cc99 # Chapter 2
    - 9352e030-3a6d-4f5f-add4-74e01d270e43 # Info Box 2
    - a227fe85-29a0-403f-b510-659257b8c521 # Text 2
    - a568129a-e9d4-406e-bafe-4dae8e4b19e8 # Task Done
    - eac3ade5-8f69-4ee2-b1df-4cc1b1e1b9b7 # Image 2
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
