columnSuffix: null
handle: lessonBlocks
instructions: null
name: 'Lesson Blocks'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    - 120a0c87-a4cf-4fb4-8e36-2533818e113a # Chapter
    - 572f6109-c32e-4df3-8c66-7e5bba2756ea # Text
    - ec8d0268-e294-4677-9a70-bf25ab9f87e7 # Info Box
    - 409d3c53-f6a8-476d-be5a-5bc8d3acc0f6 # Image
    - 13e06e3a-25c9-4b11-aa21-6b5b768d5fea # Send in answer
    - a568129a-e9d4-406e-bafe-4dae8e4b19e8 # Task Done
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
