columnSuffix: null
handle: lineNumbers
instructions: null
name: 'ContentBlocks - File Content - Line Numbers'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
