columnSuffix: null
handle: linkToAll
instructions: null
name: 'ContentBlocks - Link to all?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
