contentColumnType: string
fieldGroup: b0f70f0a-25fa-4376-b9fa-e4508bca7a85
handle: menuLink
instructions: ''
name: 'Menu link'
searchable: true
settings:
  columns:
    __assoc__:
      -
        - f598728f-d688-4b98-8aab-cf4447b3af95
        -
          __assoc__:
            -
              - width
              - ''
      -
        - f2cc0c2d-6188-407c-b0f2-e9afc9ecdb23
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_menulink}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
