columnSuffix: null
handle: menuLink
instructions: null
name: 'Menu link'
searchable: true
settings:
  contentTable: ''
  createButtonLabel: null
  entryTypes:
    - e6da2fad-eca4-4420-b3ee-ddb8e1fb8941 # Menu link Block
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: language
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
