contentColumnType: string
handle: menuLink
instructions: ''
name: 'Menu link'
searchable: true
settings:
  columns:
    __assoc__:
      -
        - f598728f-d688-4b98-8aab-cf4447b3af95
        -
          __assoc__:
            -
              - width
              - ''
      -
        - f2cc0c2d-6188-407c-b0f2-e9afc9ecdb23
        -
          __assoc__:
            -
              - width
              - ''
  entryTypes:
    - e6da2fad-eca4-4420-b3ee-ddb8e1fb8941 # Menu link Block
  fieldLayout: table
  maxEntries: null
  maxRows: ''
  minEntries: null
  minRows: ''
  placeholderKey: null
  propagationMethod: language
  selectionLabel: ''
  staticField: ''
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
