columnSuffix: null
contentColumnType: boolean
handle: noMobile
instructions: 'Show article image as blurred overlay on mobile'
name: 'Not mobile friendly'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
