columnSuffix: null
handle: review
instructions: null
name: Review
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: ab427603-a5f6-4996-858f-48231556f394 # Default
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: language
type: craft\ckeditor\Field
