columnSuffix: null
handle: review
instructions: null
name: Review
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  css: null
  cssFile: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  fullGraphqlData: false
  headingLevels:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  js: null
  jsFile: Default.json
  options: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  toolbar:
    - sourceEditing
    - '|'
    - heading
    - '|'
    - blockQuote
    - codeBlock
    - bold
    - italic
    - strikethrough
    - bulletedList
    - numberedList
    - insertImage
    - link
  wordLimit: null
translationKeyFormat: null
translationMethod: language
type: craft\ckeditor\Field
