columnSuffix: yliqoyvr
handle: selfcontained
instructions: 'Hides title and gray background wrapper'
name: Selfcontained
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
