columnSuffix: null
handle: terminalDump
instructions: null
name: 'ContentBlocks - Terminal Dump - Terminal Dump'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
