columnSuffix: null
handle: terminalInputOnly
instructions: null
name: 'ContentBlocks - Terminal Dump - Terminal Input Only'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
