columnSuffix: null
handle: text
instructions: null
name: 'ContentBlocks - Text'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: ''
  css: null
  cssFile: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  fullGraphqlData: false
  headingLevels: false
  js: null
  jsFile: Simple.json
  options: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  toolbar:
    - bold
    - italic
    - underline
    - strikethrough
    - '|'
    - subscript
    - superscript
    - '|'
    - bulletedList
    - numberedList
    - outdent
    - indent
    - '|'
    - link
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
