columnSuffix: null
handle: text
instructions: null
name: 'ContentBlocks - Text - Text'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: ''
  ckeConfig: bcea5606-ec0b-4bea-b4ab-b4c0eebb7851 # Default
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
