columnSuffix: null
handle: text
instructions: null
name: 'ContentBlocks - Text - Text'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: ''
  ckeConfig: ab427603-a5f6-4996-858f-48231556f394 # Default
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
