columnSuffix: null
handle: text
instructions: null
name: 'ContentBlocks - Text'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: ''
  ckeConfig: 4ff4b6be-5f03-4236-a01d-2b5125c03d66 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
