columnSuffix: null
handle: threeNewest
instructions: null
name: 'ContentBlocks - Books - Three newest?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
