dateModified: 1734176749
email:
  fromEmail: stanley.skarshaug@gmail.com
  fromName: craft_test
  transportType: craft\mail\transportadapters\Sendmail
fs:
  iconsAndBadges:
    hasUrls: true
    name: 'Icons and Badges'
    settings:
      path: uploads/iconsAndBadges
    type: craft\fs\Local
    url: '@web/uploads/iconsAndBadges'
  images:
    hasUrls: true
    name: Images
    settings:
      path: uploads/images
    type: craft\fs\Local
    url: '@web/uploads/images'
  pdf:
    hasUrls: true
    name: 'PDF''s'
    settings:
      path: uploads/pdf
    type: craft\fs\Local
    url: '@web/uploads/pdf'
  thumbnails:
    hasUrls: true
    name: Thumbnails
    settings:
      path: uploads/thumbnails
    type: craft\fs\Local
    url: '@web/uploads/thumbnails'
meta:
  __names__:
    0e2235ec-098b-4add-9c16-2a51cb50b5e3: 'Course Grade' # Course Grade
    0f03b5b8-d4f9-4e6c-bd6c-d8fa38c5329e: Home # Home
    1e364dce-0242-4cfe-8565-03b39ef5bea6: Certificates # Certificates
    2caebe53-52a0-4509-b4f6-865b55837d5f: 'Chart - Bar (Stacked)' # Chart - Bar (Stacked)
    2ec41ca2-210b-47c8-97d3-306955a39abb: Articles # Articles
    2fc7f7b8-2f9d-43dd-977b-8c7b29763e54: haxor.no/en # haxor.no/en
    3a65209b-542d-42a6-9fc7-a9b07fd38253: 'File Content' # File Content
    3b363f5e-4ee5-4536-b78c-b514bf1a0c7a: Images # Images
    3bbcac38-b6d8-4918-9863-bcff6b8f60d2: 'CTF Platform' # CTF Platform
    3d5543fa-7b96-4f00-baff-e330b237625b: 'Not mobile friendly' # Not mobile friendly
    3e4dc06a-6af1-479b-a120-662a4500d935: 'Artikkel tema' # Artikkel tema
    3ebdee02-2eb1-48f4-8b4b-4f45f3bfbae9: 'ContentBlocks - Terminal Dump - Username' # ContentBlocks - Terminal Dump - Username
    4a837336-d09a-492d-aa97-3c29b176ecc7: 'Course Platform' # Course Platform
    4fa3f654-1283-406b-9656-22b48a6c818e: 'Course Certificate URL' # Course Certificate URL
    4ff4b6be-5f03-4236-a01d-2b5125c03d66: Simple # Simple
    5c01d860-2ec5-4205-936e-583524bb8264: 'ContentBlocks - Image - Image AltText' # ContentBlocks - Image - Image AltText
    5d2b6ceb-3b09-44f2-ab53-25f33e506025: 'Achievement Badge' # Achievement Badge
    5dd9f4f3-fb1c-4d81-b3fd-2309b56563f0: 'ContentBlocks - File Content - Filname' # ContentBlocks - File Content - Filname
    5f92318f-a48c-4fb9-9b08-f04c9a691e87: 'CTF Writeup' # CTF Writeup
    6a498afe-8881-4b4d-bd9e-f128e6d2ac6e: 'ContentBlocks - Image - Image Caption' # ContentBlocks - Image - Image Caption
    6bcc3fb3-fa1a-42c3-b33b-5f61432e08ca: 'Artikkel type' # Artikkel type
    6d60bb4f-9586-4f12-8115-a411b6544a6e: 'Book Reviews' # Book Reviews
    6ed30be3-319a-4469-a458-a70309e3e179: 'Course Review' # Course Review
    6f1a1285-4249-4f2a-9773-1b8a2cb33fd9: Kursplatform # Kursplatform
    6f5f5cbf-7ead-4f94-9ed2-42c81ae3a3d3: 'Course Review Score' # Course Review Score
    7d9ff56a-e0ad-49f6-810e-0b4601084749: Certificate # Certificate
    7dbe180d-e397-494f-bea8-61f7b3f5bf4d: 'Book Reviews' # Book Reviews
    7dca122d-a470-466a-ae07-51758b1fc449: 'ContentBlocks - Chart - Bar (Stacked) - Chart Title' # ContentBlocks - Chart - Bar (Stacked) - Chart Title
    7e0480ca-cc52-4451-8832-4a34bfe5ea09: Thumbnails # Thumbnails
    7ed843f8-2709-4ad0-b32d-e234ed22f289: 'ContentBlocks - Terminal Dump - Color' # ContentBlocks - Terminal Dump - Color
    8c4f446d-dc3c-443f-b043-fb2a3c5e2aff: 'CTF Points' # CTF Points
    9b49d5b9-d21a-4e64-b799-37fe5db4ada8: 'ContentBlocks - Books - Three newest?' # ContentBlocks - Books - Three newest?
    9dbc0bea-5f8c-4a42-a060-58a1e9baf36f: 'ContentBlocks - Chart - Bar (Stacked) - Chart Subtitle' # ContentBlocks - Chart - Bar (Stacked) - Chart Subtitle
    9dfaa653-4e36-4b09-a7a7-e25e81bafdf7: 'ContentBlocks - Certificate - Certificates' # ContentBlocks - Certificate - Certificates
    12f99a24-9d48-4fdd-8f1e-fec6cabf9cca: Lessons # Lessons
    13e06e3a-25c9-4b11-aa21-6b5b768d5fea: 'Send in answer' # Send in answer
    15cb9ee9-280a-4a76-9b2f-d31dff2fb525: 'Number of Pages' # Number of Pages
    18efdf32-1b23-42db-a0ed-70252bb134fb: 'Terminal Dump' # Terminal Dump
    34ae23a4-8987-424f-a7af-fc651ee1f28c: HackerRank # HackerRank
    40df60cf-14a4-435a-83b3-643fc99abed3: 'Book Image' # Book Image
    43b06241-b021-46cc-8374-3f02e8a02699: Default # Default
    44f8fa56-23f3-4d1e-8231-4e7f46c9af46: 'Copletion Date' # Copletion Date
    52f10b73-e1ae-4ada-8d03-81ceafab228c: Guides # Guides
    57a8d48f-2781-4975-b7ff-b3b5efd7c470: 'ContentBlocks - Text' # ContentBlocks - Text
    058e2f74-bbca-46da-9d7b-161bcaae9844: 'Article thumbnail' # Article thumbnail
    62b88f4a-25d3-4a89-831f-24f78c24f85b: 'ContentBlocks - Chapter - Subtitle' # ContentBlocks - Chapter - Subtitle
    71ac9a76-cabc-44c7-8470-bae1c0d43ed0: 'Selected Entry' # Selected Entry
    72a349c8-b7c8-4301-81a5-7301f5cc1058: 'Article Image' # Article Image
    77ba99a9-9415-421c-ae85-9f5452850a48: 'Public Schema' # Public Schema
    080d70ab-85ac-424a-9d06-3aedf3fd9889: Globals # Globals
    93d39a6a-48eb-4f78-afb1-8fd74053ce15: 'Course Image' # Course Image
    120a0c87-a4cf-4fb4-8e36-2533818e113a: Chapter # Chapter
    144bdcbe-f6e4-4f3f-bede-6f627cd7f0dd: Credits # Credits
    268e169b-dff4-4e90-ad5a-8618c54e799e: 'Lesson Blocks - Send in answer - Question' # Lesson Blocks - Send in answer - Question
    392f9448-cfdd-4390-ab2b-7bdce2deeb89: Writer # Writer
    409d3c53-f6a8-476d-be5a-5bc8d3acc0f6: Image # Image
    515bc6fb-894b-442b-8af3-6666bef0300f: Kurs # Kurs
    572f6109-c32e-4df3-8c66-7e5bba2756ea: Text # Text
    704a8478-65c0-4619-87e8-0b570ccd42f4: Publisher # Publisher
    849ea203-a4f7-42a8-845c-45933a0ee48a: 'Menu link' # Menu link
    1123b472-8241-4d07-bd52-1eff0c59f1ef: 'About Blog' # About Blog
    4660b070-063e-4eb7-b897-c5273ae300c3: 'Icons and Badges' # Icons and Badges
    5084e704-59ac-4ed3-bc26-1b3b96710a82: 'Lesson Blocks - Send in answer - Answer' # Lesson Blocks - Send in answer - Answer
    5551a1b5-fa8d-41d6-b7c3-af16e2ea9981: 'CTF Writeups' # CTF Writeups
    6288f6a3-5828-4e36-8407-4f1fbe59e057: 'Achievement Badge' # Achievement Badge
    6799dd35-5fb9-4623-b487-3aafaf92ec39: blog # blog
    7536d724-07df-42bd-b0fe-a872ad23ac5a: 'Above Content' # Above Content
    7648fab9-2bab-43df-adca-9f3d941c929e: Artikkeltype # Artikkeltype
    7701d10a-74fb-40fb-a7aa-7e184bb97f05: 'SEO Image' # SEO Image
    7755a334-0698-4415-ab30-b1fddb17b7a7: Tema # Tema
    9096bb19-2f4d-4b40-91f7-7f0d84ee7b01: 'Course Length (hours)' # Course Length (hours)
    19285c32-e1f8-42c0-97ff-59f16dbb52af: 'ContentBlocks - Terminal Dump - Hostname' # ContentBlocks - Terminal Dump - Hostname
    023232ef-4d79-4571-896b-9146438b66bb: 'Lesson Blocks - Task Done - Task text' # Lesson Blocks - Task Done - Task text
    040290e0-e763-4e3c-8e18-5610e6e0864f: 'THM scoreboard' # THM scoreboard
    64860ba2-3393-423d-950c-d23a278d4d20: Entry # Entry
    88680ae0-eeb1-4709-b620-2e2a9f91b4a6: 'CTF Writeup - Default' # CTF Writeup - Default
    190326da-4559-4d36-aae0-20b00fa6318f: Books # Books
    315547ae-9f46-441e-831a-f2979d046b94: 'About Me' # About Me
    433733b6-53ef-4e88-b871-7518468484e7: Portfolio # Portfolio
    588083f4-9c65-4945-9298-df03cd87f06e: 'About Me' # About Me
    925133d6-79dc-4f13-9cbc-3752c2eff691: 'ContentBlocks - Terminal Dump - Terminal Dump' # ContentBlocks - Terminal Dump - Terminal Dump
    82658716-4746-4ec3-9c32-b565286277bc: 'CTF Difficulty' # CTF Difficulty
    84196158-704f-46cd-9cc5-cfe49666f56e: Intro # Intro
    a2c9fa7f-4706-4b49-ad49-f09d9a9ebc10: 'ContentBlocks - Courses - Courses' # ContentBlocks - Courses - Courses
    a568129a-e9d4-406e-bafe-4dae8e4b19e8: 'Task Done' # Task Done
    aad6c628-7e5f-4c95-9383-e39426be72f7: 'CTF Image' # CTF Image
    ab427603-a5f6-4996-858f-48231556f394: Default # Default
    ac49e4c4-d11a-4bbe-9a08-04c06268ba93: 'Course Length (min)' # Course Length (min)
    af5a6f2d-4fdf-4cfe-b5e8-900a1ae088c5: 'ContentBlocks - Link to all?' # ContentBlocks - Link to all?
    b04f4663-1608-479d-b699-ba1102ba1b61: 'Article Headline' # Article Headline
    b05c4334-9b2d-4f18-8916-c65a9c521861: 'ContentBlocks - Image - Image' # ContentBlocks - Image - Image
    b5a3273e-575f-489d-a09a-c407248dc831: 'CTF Writeups' # CTF Writeups
    b47d1535-bf95-4240-8817-43e15b459bc1: Headline # Headline
    b92f222e-e35a-4a5a-bb11-3b5ea3deda0c: Quote # Quote
    b3979b7e-2d54-4b6f-89ec-5ef480431d82: Courses # Courses
    b4763ae9-35a9-4af6-bd45-59e869963a55: 'Internal link' # Internal link
    b25947e8-fbe4-4dbb-a968-90f7659c7d7f: Home # Home
    c2cadeae-b406-4376-a7bb-822c8d077ca2: 'Course Theme' # Course Theme
    c3d8fdbe-5d3a-4a09-a91f-2da6060ece41: ContentBlocks # ContentBlocks
    c6f23113-dc98-46d8-8a58-8837396917aa: 'CTF Platfom' # CTF Platfom
    c418c358-5082-4c2e-bc17-cb8c9175b592: Instructor # Instructor
    c4023ed4-c787-4f58-bb1f-1d51b48518c2: Books # Books
    c1769912-6758-4fbd-9f12-d37a9fa32253: 'SEO Description' # SEO Description
    cabe8fa0-a9ef-4a18-ab9d-4b3b69cd2f3a: 'ContentBlocks - Terminal Dump - Terminal Input Only' # ContentBlocks - Terminal Dump - Terminal Input Only
    ce283fd6-8942-4408-99bf-17efbab5a118: Books # Books
    d2ea4108-edc5-4f74-9794-214619a9f0c8: 'My courses' # My courses
    d6f9cc1f-1608-4ae7-a083-d0924ba71f47: 'ContentBlocks - Image - Image Is Figure' # ContentBlocks - Image - Image Is Figure
    d9a0abe6-89dd-4688-a0ac-6d584524c3c2: 'Course Certificate' # Course Certificate
    d67ba21e-e565-441c-aafd-bee2a9f4d3f7: 'ContentBlocks - Chart - Bar (Stacked) - Data' # ContentBlocks - Chart - Bar (Stacked) - Data
    d81b7a18-6d93-471a-ba57-99544b0c585b: haxor.no/no # haxor.no/no
    dc32cdca-de36-4628-af9c-221eb639a9ab: 'PDF''s' # PDF's
    dc63f038-3a87-428d-9230-20a288f905da: 'ContentBlocks - File Content - File type' # ContentBlocks - File Content - File type
    dc9122fb-758f-42ae-a098-da603eb31a49: Courses # Courses
    e6da2fad-eca4-4420-b3ee-ddb8e1fb8941: 'Menu link' # Menu link
    e75f8e08-e499-444e-b646-97309e1abb2b: 'ContentBlocks - Books - Books' # ContentBlocks - Books - Books
    ea9728b1-b326-481a-810f-1735e2b682cc: TryHackMe # TryHackMe
    ec8d0268-e294-4677-9a70-bf25ab9f87e7: 'Info Box' # Info Box
    ec9f430a-d961-4e4c-ab37-d8de33b78cbe: 'Lesson Blocks' # Lesson Blocks
    ed01c0d7-346e-4af2-b76f-825ac0da9e30: 'My courses' # My courses
    ed90e740-711b-4901-9c4f-56ea797d242e: Certificates # Certificates
    ed101e61-62b0-40c5-a8d4-b5d30624f1d2: 'ContentBlocks - File Content - File content' # ContentBlocks - File Content - File content
    f2cc0c2d-6188-407c-b0f2-e9afc9ecdb23: 'Menu link - Text' # Menu link - Text
    f8f50449-6440-4878-a1c7-8da852defe91: 'Chart - Line' # Chart - Line
    f73c4dce-8cb4-431f-adb5-a9be1f4059cb: 'ContentBlocks - Terminal Dump - Language' # ContentBlocks - Terminal Dump - Language
    f96fb1c8-21d9-45ec-bc75-5792dd3b3c5b: 'ContentBlocks - Quote - Quote' # ContentBlocks - Quote - Quote
    f147e4fb-5b9b-40b9-9b58-51fa33d89e32: Teaser # Teaser
    f490c527-58d9-4ac9-bbba-4b4b537e6e0b: Description # Description
    f733eaac-e1d6-428e-a5e6-5e9c1b8450df: 'Review Quote' # Review Quote
    f9145c5e-c78a-4a33-950f-a91359723426: Selfcontained # Selfcontained
    f4121429-712b-4587-839a-e0a1db5d946a: 'ContentBlocks - File Content - Line Numbers' # ContentBlocks - File Content - Line Numbers
    fc40ce26-28fb-475a-b6b7-696c795f5f18: 'Simple text and link' # Simple text and link
    fe6324d5-2558-4ab4-99f2-f424b8051892: 'About Blog' # About Blog
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  haxor:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  tryhackme:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      country: '164'
      countryCompetition:
        - '59'
        - '73'
        - '85'
        - '164'
        - '211'
      username: mEsUsah
system:
  edition: solo
  live: true
  name: haxor.no
  retryDuration: null
  schemaVersion: 5.5.0.0
  timeZone: Europe/Oslo
