dateModified: 1718911624
email:
  fromEmail: stanley.skarshaug@gmail.com
  fromName: craft_test
  transportType: craft\mail\transportadapters\Sendmail
fs:
  iconsAndBadges:
    hasUrls: true
    name: 'Icons and Badges'
    settings:
      path: uploads/iconsAndBadges
    type: craft\fs\Local
    url: '@web/uploads/iconsAndBadges'
  images:
    hasUrls: true
    name: Images
    settings:
      path: uploads/images
    type: craft\fs\Local
    url: '@web/uploads/images'
  pdf:
    hasUrls: true
    name: 'PDF''s'
    settings:
      path: uploads/pdf
    type: craft\fs\Local
    url: '@web/uploads/pdf'
  thumbnails:
    hasUrls: true
    name: Thumbnails
    settings:
      path: uploads/thumbnails
    type: craft\fs\Local
    url: '@web/uploads/thumbnails'
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0e2235ec-098b-4add-9c16-2a51cb50b5e3: 'Course Grade' # Course Grade
    0f03b5b8-d4f9-4e6c-bd6c-d8fa38c5329e: Home # Home
    1e364dce-0242-4cfe-8565-03b39ef5bea6: Certificates # Certificates
    2ec41ca2-210b-47c8-97d3-306955a39abb: Articles # Articles
    2fc7f7b8-2f9d-43dd-977b-8c7b29763e54: haxor.no/en # haxor.no/en
    3b363f5e-4ee5-4536-b78c-b514bf1a0c7a: Images # Images
    3bbcac38-b6d8-4918-9863-bcff6b8f60d2: 'CTF Platform' # CTF Platform
    3d5543fa-7b96-4f00-baff-e330b237625b: 'Not mobile friendly' # Not mobile friendly
    3e4dc06a-6af1-479b-a120-662a4500d935: 'Artikkel tema' # Artikkel tema
    4a837336-d09a-492d-aa97-3c29b176ecc7: 'Course Platform' # Course Platform
    4fa3f654-1283-406b-9656-22b48a6c818e: 'Course Certificate URL' # Course Certificate URL
    5d2b6ceb-3b09-44f2-ab53-25f33e506025: 'Achievement Badge' # Achievement Badge
    5f92318f-a48c-4fb9-9b08-f04c9a691e87: 'CTF Writeup' # CTF Writeup
    6bcc3fb3-fa1a-42c3-b33b-5f61432e08ca: 'Artikkel type' # Artikkel type
    6d60bb4f-9586-4f12-8115-a411b6544a6e: 'Book Reviews' # Book Reviews
    6ed30be3-319a-4469-a458-a70309e3e179: 'Course Review' # Course Review
    6f1a1285-4249-4f2a-9773-1b8a2cb33fd9: Kursplatform # Kursplatform
    6f5f5cbf-7ead-4f94-9ed2-42c81ae3a3d3: 'Course Review Score' # Course Review Score
    7dbe180d-e397-494f-bea8-61f7b3f5bf4d: 'Book Reviews' # Book Reviews
    7e0480ca-cc52-4451-8832-4a34bfe5ea09: Thumbnails # Thumbnails
    8c4f446d-dc3c-443f-b043-fb2a3c5e2aff: 'CTF Points' # CTF Points
    12c8b9da-5b5a-4bd7-a51e-4116181081ad: 'Course Description' # Course Description
    12f99a24-9d48-4fdd-8f1e-fec6cabf9cca: Lessons # Lessons
    15cb9ee9-280a-4a76-9b2f-d31dff2fb525: 'Number of Pages' # Number of Pages
    40df60cf-14a4-435a-83b3-643fc99abed3: 'Book Image' # Book Image
    43b06241-b021-46cc-8374-3f02e8a02699: Default # Default
    44f8fa56-23f3-4d1e-8231-4e7f46c9af46: 'Copletion Date' # Copletion Date
    049ddb67-9315-429c-9494-0cf452f8cb73: Stack # Stack
    52f10b73-e1ae-4ada-8d03-81ceafab228c: Guides # Guides
    058e2f74-bbca-46da-9d7b-161bcaae9844: 'Article thumbnail' # Article thumbnail
    72a349c8-b7c8-4301-81a5-7301f5cc1058: 'Article Image' # Article Image
    080d70ab-85ac-424a-9d06-3aedf3fd9889: Globals # Globals
    93d39a6a-48eb-4f78-afb1-8fd74053ce15: 'Course Image' # Course Image
    286c04a5-6631-4fb0-a891-256488a130e9: 'Image Caption' # Image Caption
    386c4702-8fb5-4d6d-8e99-f43e77541a6d: 'Image AltText' # Image AltText
    392f9448-cfdd-4390-ab2b-7bdce2deeb89: Writer # Writer
    515bc6fb-894b-442b-8af3-6666bef0300f: Kurs # Kurs
    704a8478-65c0-4619-87e8-0b570ccd42f4: Publisher # Publisher
    849ea203-a4f7-42a8-845c-45933a0ee48a: 'Menu link' # Menu link
    1079ffac-f516-4c4f-a131-3a26fa26ac15: 'Image Is Figure' # Image Is Figure
    1123b472-8241-4d07-bd52-1eff0c59f1ef: 'About Blog' # About Blog
    4660b070-063e-4eb7-b897-c5273ae300c3: 'Icons and Badges' # Icons and Badges
    5551a1b5-fa8d-41d6-b7c3-af16e2ea9981: 'CTF Writeups' # CTF Writeups
    6288f6a3-5828-4e36-8407-4f1fbe59e057: 'Achievement Badge' # Achievement Badge
    6799dd35-5fb9-4623-b487-3aafaf92ec39: blog # blog
    7536d724-07df-42bd-b0fe-a872ad23ac5a: 'Above Content' # Above Content
    7648fab9-2bab-43df-adca-9f3d941c929e: Artikkeltype # Artikkeltype
    7701d10a-74fb-40fb-a7aa-7e184bb97f05: 'SEO Image' # SEO Image
    7755a334-0698-4415-ab30-b1fddb17b7a7: Tema # Tema
    9096bb19-2f4d-4b40-91f7-7f0d84ee7b01: 'Course Length (hours)' # Course Length (hours)
    20919efd-3398-44c3-83c8-d9ee3cdcdf33: 'Terminal Prompt' # Terminal Prompt
    040290e0-e763-4e3c-8e18-5610e6e0864f: 'THM scoreboard' # THM scoreboard
    88680ae0-eeb1-4709-b620-2e2a9f91b4a6: 'CTF Writeup - Default' # CTF Writeup - Default
    190326da-4559-4d36-aae0-20b00fa6318f: Books # Books
    315547ae-9f46-441e-831a-f2979d046b94: 'About Me' # About Me
    433733b6-53ef-4e88-b871-7518468484e7: Portfolio # Portfolio
    588083f4-9c65-4945-9298-df03cd87f06e: 'About Me' # About Me
    82658716-4746-4ec3-9c32-b565286277bc: 'CTF Difficulty' # CTF Difficulty
    84196158-704f-46cd-9cc5-cfe49666f56e: Intro # Intro
    a6bd78d7-41d8-4db7-8a28-70f5638e4b88: 'Link to all certifications?' # Link to all certifications?
    aad6c628-7e5f-4c95-9383-e39426be72f7: 'CTF Image' # CTF Image
    ac49e4c4-d11a-4bbe-9a08-04c06268ba93: 'Course Length (min)' # Course Length (min)
    b04f4663-1608-479d-b699-ba1102ba1b61: 'Article Headline' # Article Headline
    b5a3273e-575f-489d-a09a-c407248dc831: 'CTF Writeups' # CTF Writeups
    b3979b7e-2d54-4b6f-89ec-5ef480431d82: Courses # Courses
    b4763ae9-35a9-4af6-bd45-59e869963a55: 'Internal link' # Internal link
    b25947e8-fbe4-4dbb-a968-90f7659c7d7f: Home # Home
    baecef3d-6c25-40bf-8e85-eeedf43dec57: 'Rich text' # Rich text
    baf14ed6-b329-41e7-b9b5-4ff5d8ed2cdf: 'Article Image Caption' # Article Image Caption
    c2cadeae-b406-4376-a7bb-822c8d077ca2: 'Course Theme' # Course Theme
    c3d8fdbe-5d3a-4a09-a91f-2da6060ece41: ContentBlocks # ContentBlocks
    c6f23113-dc98-46d8-8a58-8837396917aa: 'CTF Platfom' # CTF Platfom
    c418c358-5082-4c2e-bc17-cb8c9175b592: Instructor # Instructor
    c4023ed4-c787-4f58-bb1f-1d51b48518c2: Books # Books
    c1769912-6758-4fbd-9f12-d37a9fa32253: 'SEO Description' # SEO Description
    d2ea4108-edc5-4f74-9794-214619a9f0c8: 'My courses' # My courses
    d9a0abe6-89dd-4688-a0ac-6d584524c3c2: 'Course Certificate' # Course Certificate
    d81b7a18-6d93-471a-ba57-99544b0c585b: haxor.no/no # haxor.no/no
    dc32cdca-de36-4628-af9c-221eb639a9ab: 'PDF''s' # PDF's
    e6da2fad-eca4-4420-b3ee-ddb8e1fb8941: 'Menu link Block' # Menu link Block
    ec9f430a-d961-4e4c-ab37-d8de33b78cbe: 'Lesson Blocks' # Lesson Blocks
    ed01c0d7-346e-4af2-b76f-825ac0da9e30: 'My courses' # My courses
    ed90e740-711b-4901-9c4f-56ea797d242e: 'Certificates - Default' # Certificates - Default
    f29cf56f-e024-4426-a529-899246ced721: Image # Image
    f147e4fb-5b9b-40b9-9b58-51fa33d89e32: 'Article Teaser' # Article Teaser
    f733eaac-e1d6-428e-a5e6-5e9c1b8450df: 'Course Review Quote' # Course Review Quote
    f9145c5e-c78a-4a33-950f-a91359723426: Selfcontained # Selfcontained
    fe6324d5-2558-4ab4-99f2-f424b8051892: 'About Blog' # About Blog
plugins:
  haxor:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  tryhackme:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      country: '164'
      countryCompetition:
        - '59'
        - '73'
        - '85'
        - '164'
        - '211'
      username: mEsUsah
system:
  edition: solo
  live: true
  name: haxor.no
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: Europe/Oslo
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
