fieldLayouts:
  0d1b50fc-6bfd-4083-bdb1-ece4686cbec8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 849ea203-a4f7-42a8-845c-45933a0ee48a # Menu link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f885baa-7120-4709-8a67-65664f83b6fc
            userCondition: null
            warning: null
            width: 100
        name: Gobals
        uid: e54f2b2c-1476-41b6-9f60-8b11200feded
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7701d10a-74fb-40fb-a7aa-7e184bb97f05 # SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b04154d3-6bda-4d0d-89a1-d6e0071f41e4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c1769912-6758-4fbd-9f12-d37a9fa32253 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5bf92a6-b4ef-4fdb-b540-48af88b74d61
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 55d62030-404c-47b4-9bf3-4faf6bd3e6d1
        userCondition: null
handle: globals
name: Globals
sortOrder: 2
