defaultPlacement: end
enableVersioning: true
entryTypes:
  - 588083f4-9c65-4945-9298-df03cd87f06e # About Me
handle: aboutme
maxAuthors: 1
name: 'About Me'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  2fc7f7b8-2f9d-43dd-977b-8c7b29763e54: # haxor.no/en
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: about-me
  d81b7a18-6d93-471a-ba57-99544b0c585b: # haxor.no/no
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: om-meg
type: single
