defaultPlacement: end
enableVersioning: true
handle: aboutblog
name: 'About Blog'
propagationMethod: all
siteSettings:
  2fc7f7b8-2f9d-43dd-977b-8c7b29763e54: # haxor.no/en
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: about-blog
  d81b7a18-6d93-471a-ba57-99544b0c585b: # haxor.no/no
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: om-bloggen
type: single
