defaultPlacement: end
enableVersioning: true
entryTypes:
  - 52f10b73-e1ae-4ada-8d03-81ceafab228c # Guides
handle: articles
maxAuthors: 1
name: Articles
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: custom
siteSettings:
  2fc7f7b8-2f9d-43dd-977b-8c7b29763e54: # haxor.no/en
    enabledByDefault: false
    hasUrls: true
    template: index
    uriFormat: 'article/{slug}'
  d81b7a18-6d93-471a-ba57-99544b0c585b: # haxor.no/no
    enabledByDefault: false
    hasUrls: true
    template: index
    uriFormat: 'artikkel/{slug}'
type: channel
