defaultPlacement: end
enableVersioning: true
entryTypes:
  - ed90e740-711b-4901-9c4f-56ea797d242e # Certificates - Default
handle: certificates
maxAuthors: 1
name: Certificates
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: custom
siteSettings:
  2fc7f7b8-2f9d-43dd-977b-8c7b29763e54: # haxor.no/en
    enabledByDefault: false
    hasUrls: true
    template: index
    uriFormat: 'certifications/{slug}'
  d81b7a18-6d93-471a-ba57-99544b0c585b: # haxor.no/no
    enabledByDefault: false
    hasUrls: true
    template: index
    uriFormat: 'sertifiseringer/{slug}'
type: channel
