defaultPlacement: end
enableVersioning: true
handle: ctfWriteup
name: 'CTF Writeup'
propagationMethod: custom
siteSettings:
  2fc7f7b8-2f9d-43dd-977b-8c7b29763e54: # haxor.no/en
    enabledByDefault: false
    hasUrls: true
    template: index
    uriFormat: 'ctf-writeup/{slug}'
type: channel
