defaultPlacement: end
enableVersioning: true
handle: ctfWriteups
name: 'CTF Writeups'
propagationMethod: all
siteSettings:
  2fc7f7b8-2f9d-43dd-977b-8c7b29763e54: # haxor.no/en
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: ctf-writeup
type: single
