defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7536d724-07df-42bd-b0fe-a872ad23ac5a # Above Content
  - 040290e0-e763-4e3c-8e18-5610e6e0864f # THM scoreboard
handle: portfolio
maxAuthors: 1
name: Portfolio
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: custom
siteSettings:
  2fc7f7b8-2f9d-43dd-977b-8c7b29763e54: # haxor.no/en
    enabledByDefault: false
    hasUrls: true
    template: index
    uriFormat: 'portfolio/{slug}'
  d81b7a18-6d93-471a-ba57-99544b0c585b: # haxor.no/no
    enabledByDefault: false
    hasUrls: true
    template: index
    uriFormat: 'portfolio/{slug}'
type: channel
