enableVersioning: true
handle: portfolio
name: Portfolio
propagationMethod: all
siteSettings:
  2fc7f7b8-2f9d-43dd-977b-8c7b29763e54: # Skarshaugs.no/en
    enabledByDefault: false
    hasUrls: true
    template: index
    uriFormat: 'portfolio/{slug}'
  d81b7a18-6d93-471a-ba57-99544b0c585b: # Skarshaugs.no
    enabledByDefault: false
    hasUrls: true
    template: index
    uriFormat: 'portfolio/{slug}'
type: channel
